package com.leweiyou.service.service;

import org.springframework.beans.factory.annotation.Autowired;
import com.github.pagehelper.PageHelper;import com.github.pagehelper.PageInfo;import com.leweiyou.service.mybatis.dao.TUserCopyMapper;


import com.leweiyou.service.mybatis.entry.TUserCopy;
import com.leweiyou.service.mybatis.entry.TUserCopyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public abstract class _TUserCopyService{

	@Autowired
	private TUserCopyMapper tUserCopyMapper;

	public PageInfo<TUserCopy> selectByExample(TUserCopyExample e,int offer, int limit) {
		PageHelper.startPage(offer, limit);
		PageInfo<TUserCopy> page = new PageInfo<TUserCopy>(tUserCopyMapper.selectByExample(e));
		return page;
	}

 	public TUserCopy selectOne(TUserCopyExample example){
	 	List<TUserCopy> list = tUserCopyMapper.selectByExample(example);
     	return (list == null || list.size() == 0) ? null : list.get(0);
 	}


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int countByExample(TUserCopyExample example){
        return tUserCopyMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int deleteByExample(TUserCopyExample example){
        return tUserCopyMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int deleteByPrimaryKey(Long id){
        return tUserCopyMapper.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int insert(TUserCopy record){
        return tUserCopyMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int insertSelective(TUserCopy record){
        return tUserCopyMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     List<TUserCopy> selectByExampleWithBLOBs(TUserCopyExample example){
        return tUserCopyMapper.selectByExampleWithBLOBs(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     List<TUserCopy> selectByExample(TUserCopyExample example){
        return tUserCopyMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     TUserCopy selectByPrimaryKey(Long id){
        return tUserCopyMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByExampleSelective(TUserCopy record, TUserCopyExample example){
         return tUserCopyMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByExampleWithBLOBs(TUserCopy record, TUserCopyExample example){
         return tUserCopyMapper.updateByExampleWithBLOBs(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByExample(TUserCopy record, TUserCopyExample example){
         return tUserCopyMapper.updateByExample(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKeySelective(TUserCopy record){
        return tUserCopyMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKeyWithBLOBs(TUserCopy record){
        return tUserCopyMapper.updateByPrimaryKeyWithBLOBs(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_copy
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKey(TUserCopy record){
        return tUserCopyMapper.updateByPrimaryKey(record);
    }
}
