package com.leweiyou.service.service;

import org.springframework.beans.factory.annotation.Autowired;
import com.github.pagehelper.PageHelper;import com.github.pagehelper.PageInfo;import com.leweiyou.service.mybatis.dao.TUserLoginMapper;


import com.leweiyou.service.mybatis.entry.TUserLogin;
import com.leweiyou.service.mybatis.entry.TUserLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public abstract class _TUserLoginService{

	@Autowired
	private TUserLoginMapper tUserLoginMapper;

	public PageInfo<TUserLogin> selectByExample(TUserLoginExample e,int offer, int limit) {
		PageHelper.startPage(offer, limit);
		PageInfo<TUserLogin> page = new PageInfo<TUserLogin>(tUserLoginMapper.selectByExample(e));
		return page;
	}

 	public TUserLogin selectOne(TUserLoginExample example){
	 	List<TUserLogin> list = tUserLoginMapper.selectByExample(example);
     	return (list == null || list.size() == 0) ? null : list.get(0);
 	}


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int countByExample(TUserLoginExample example){
        return tUserLoginMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int deleteByExample(TUserLoginExample example){
        return tUserLoginMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int deleteByPrimaryKey(Long id){
        return tUserLoginMapper.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int insert(TUserLogin record){
        return tUserLoginMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int insertSelective(TUserLogin record){
        return tUserLoginMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     List<TUserLogin> selectByExampleWithBLOBs(TUserLoginExample example){
        return tUserLoginMapper.selectByExampleWithBLOBs(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     List<TUserLogin> selectByExample(TUserLoginExample example){
        return tUserLoginMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     TUserLogin selectByPrimaryKey(Long id){
        return tUserLoginMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByExampleSelective(TUserLogin record, TUserLoginExample example){
         return tUserLoginMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByExampleWithBLOBs(TUserLogin record, TUserLoginExample example){
         return tUserLoginMapper.updateByExampleWithBLOBs(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByExample(TUserLogin record, TUserLoginExample example){
         return tUserLoginMapper.updateByExample(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKeySelective(TUserLogin record){
        return tUserLoginMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKeyWithBLOBs(TUserLogin record){
        return tUserLoginMapper.updateByPrimaryKeyWithBLOBs(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
	public     int updateByPrimaryKey(TUserLogin record){
        return tUserLoginMapper.updateByPrimaryKey(record);
    }
}
